<div class="container">
    <div class="row form">
        <div class="col-4">
            <form method="post" action="room">
                <div class="form-group">
                    <input class="form-control" type="text" placeholder="Ime sobe" name="roomName">
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" placeholder="Geslo" name="roomPassword">
                </div>
                <div class="form-group">
                    <a href="/room" class="btn btn-info">Generiraj sobo</a>
                    <a href="/roomOptions" class="btn btn-info">Nazaj</a>
                </div>
            </form>
        </div>
    </div>
</div>