<div class="container align-self-center home_container">
    <div class="row justify-content-center">
        <div class="col-4">
            <form method="post" action="">
                <div class="form-group">
                    <input class="form-control" type="text" placeholder="Ime" name="name">
                </div>
                <div class="form-group">
                    <input class="form-control" type="text" placeholder="Uporabniško Ime" name="username">
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" placeholder="Geslo" name="password">
                </div>
                <div class="form-group">
                    <button class="btn btn-info">Registracija</button>
                </div>
            </form>
        </div>
    </div>
</div>