<div class="container">
    <div class="row form">
        <div class="col-4">
            <form method="post">
                <div class="form-group">
                    <input class="form-control" type="text" placeholder="Uporabniško Ime" name="username">
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" placeholder="Geslo" name="password">
                </div>
                <div class="form-group">
                    <a href="/roomOptions" class="btn btn-info btn-block">Vpis</a>
                </div>
            </form>
        </div>
    </div>
</div>